### ISSUE TITLE
Latest mod release (v1.4.0) causes crash on launch with Minecraft v1.20.6

### ISSUE THREAD

**Issue by Abbanon** [HeyBlack233/RepeaterClickingSoundMod#5]
[crash log.txt](https://github.com/HeyBlack233/RepeaterSoundMod/files/15451362/crash.log.txt)

**Comment by HeyBlack233** [comment]
Sorry for really late reply to the issue, 1.20.6 support has been added in the latest release (v1.5.0) :)
